name: Build .exe for Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest # Use the latest Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11 # Set Python version for the build

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  
          pip install pyinstaller

      - name: Build the .exe file
        run: |
          pyinstaller --onefile --add-data "data;data" --add-data "pages;pages" --add-data "setup;setup" run_term.py

      - name: Upload .exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: zachto_built-exe
          path: dist/*
